spring:
  application:
    name: scoring-service
  datasource:
    url: jdbc:postgresql://localhost:5432/scoring-service-db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      group-id: scoring-service
      auto-offset-reset: earliest

server:
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  show-actuator: true

scoring:
  credit-applications-actual-period-days: 30
  min-overdue-amount: 500
  batch-size: 8
  parallelism: 8
  actual-time: 1d