services:
  activemq:
    image: apache/activemq-classic:6.1.2
    ports:
      - '61616:61616'
      - '8161:8161'

  dispatcher:
    build: dispatcher
    environment:
      - 'SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616'
    ports:
      - '8080:8080'
    depends_on:
      - activemq

  worker:
    build: worker
    environment:
      - 'SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616'
    depends_on:
      - activemq
      - dispatcher
    scale: ${WORKER_SCALE}